---
# ConfigMap pour l'application Spring Boot
apiVersion: v1
kind: ConfigMap
metadata:
  name: student-config
  namespace: devops
data:
  SPRING_APPLICATION_NAME: "student-management"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/studentdb?createDatabaseIfNotExist=true"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SERVER_PORT: "8089"
  SERVER_SERVLET_CONTEXT_PATH: "/student"
  SONAR_PROJECTKEY: "jenkins"
  SONAR_HOST_URL: "http://sonarqube-service:9000"
  SONAR_JAVA_BINARIES: "target/classes"
---
# Secret pour les données sensibles
apiVersion: v1
kind: Secret
metadata:
  name: student-secret
  namespace: devops
type: Opaque
data:
  mysql-root-password: Y2hlZGx5Cg==  # "chedly" encodé en base64
  sonar-token: MGI5MDRhMTNiMjRjZWZhNDY0YWM1ZGY0NjM5YWJlNGQ4ZTBjNDAzYQ==