---
# ConfigMap pour l'application Spring Boot
apiVersion: v1
kind: ConfigMap
metadata:
  name: student-config
  namespace: devops
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/studentdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.MySQL8Dialect"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
  SPRING_APPLICATION_NAME: "student-management"
  SERVER_PORT: "8089"
  SERVER_SERVLET_CONTEXT_PATH: "/student"
  LOGGING_LEVEL_ORG_HIBERNATE: "DEBUG"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_ORM_JPA: "DEBUG"
---
# Secret pour les données sensibles
apiVersion: v1
kind: Secret
metadata:
  name: student-secret
  namespace: devops
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "chedly"
  SONAR_TOKEN: "0b904a13b24cefa464ac5df4639abe4d8e0c403a"