---
# Service Spring Boot (NodePort)
apiVersion: v1
kind: Service
metadata:
  name: student-service
  namespace: devops
spec:
  selector:
    app: student-management
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
      nodePort: 30089
  type: NodePort
---
# Deployment Spring Boot
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-deployment
  namespace: devops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: student-management
  template:
    metadata:
      labels:
        app: student-management
    spec:
      containers:
      - name: student-app
        image: chedlyrebai/student-management-app:latest
        ports:
        - containerPort: 8089
        env:
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: student-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: student-config
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: student-secret
              key: SPRING_DATASOURCE_PASSWORD
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          valueFrom:
            configMapKeyRef:
              name: student-config
              key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        - name: SPRING_JPA_DATABASE_PLATFORM
          valueFrom:
            configMapKeyRef:
              name: student-config
              key: SPRING_JPA_DATABASE_PLATFORM
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          valueFrom:
            configMapKeyRef:
              name: student-config
              key: SPRING_JPA_HIBERNATE_DDL_AUTO
        - name: SPRING_JPA_SHOW_SQL
          valueFrom:
            configMapKeyRef:
              name: student-config
              key: SPRING_JPA_SHOW_SQL
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
          valueFrom:
            configMapKeyRef:
              name: student-config
              key: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
        - name: SPRING_APPLICATION_NAME
          valueFrom:
            configMapKeyRef:
              name: student-config
              key: SPRING_APPLICATION_NAME
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: student-config
              key: SERVER_PORT
        - name: SERVER_SERVLET_CONTEXT_PATH
          valueFrom:
            configMapKeyRef:
              name: student-config
              key: SERVER_SERVLET_CONTEXT_PATH
        - name: LOGGING_LEVEL_ORG_HIBERNATE
          valueFrom:
            configMapKeyRef:
              name: student-config
              key: LOGGING_LEVEL_ORG_HIBERNATE
        - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_ORM_JPA
          valueFrom:
            configMapKeyRef:
              name: student-config
              key: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_ORM_JPA
        - name: SPRING_CONFIG_LOCATION
          value: "optional:classpath:/"
        readinessProbe:
          httpGet:
            path: /student/actuator/health
            port: 8089
          initialDelaySeconds: 120
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /student/actuator/health
            port: 8089
          initialDelaySeconds: 180
          periodSeconds: 15